language: cpp
compiler: gcc
install:
- cat /etc/*-release
- echo `echo 2 | sudo update-alternatives --config gcc`
- sudo add-apt-repository --yes ppa:kubuntu-ppa/backports
- sudo apt-get update
- sudo apt-get install -qq -y cmake gdb
script: pwd && mkdir dist && mkdir build && cd build && cmake .. && make && make package
