sudo: required

language: cpp
services:
  - docker

env:
  global:
    secure: X7vYsdnuullrVSCuHtTdO9m252YBijzqXzsaj0QIqS45vUrqafY7QS4B2/QYpEX14LN3G9/KjSO/QntY9v6xOsfH1KwhTpCRpjRataivi8uaYGK5LwL7mf3kmNeWbl4jzyUrXDcL9a2JReKlCtAGbNs73NcIMuHhXbqlJBr0Pus=

before_install:
  - docker pull ubuntu:16.04 
  - docker pull ubuntu:14.04 

script:
- docker build 
    --tag svmtoolpp-ubuntu16
    --build-arg BINTRAYKEY=$BINTRAYKEY  
    --build-arg TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER 
    -f ./Dockerfile-ubuntu16.04 .
- docker build 
    --tag svmtoolpp-ubuntu14
    --build-arg BINTRAYKEY=$BINTRAYKEY  
    --build-arg TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER 
    -f ./Dockerfile-ubuntu14.04 .

after_success:
  - docker run -t -d svmtoolpp-ubuntu16
  - docker cp $(docker ps -n 1 -q):/src/svmtool-cpp/build/svmtool-cpp-1.1.7-Linux.deb /svmtool-cpp-1.1.7-ubuntu16.deb
  - docker run -t -d svmtoolpp-ubuntu14
  - docker cp $(docker ps -n 1 -q):/src/svmtool-cpp/build/svmtool-cpp-1.1.7-Linux.deb /svmtool-cpp-1.1.7-ubuntu14.deb

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Gael de Chalendar"
  - git config --local user.email "kleag@free.fr"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key:
    secure: 7Foj3lZkf/dPni4jgHBbSH7LQjOGd8f+XP+lBt32JCHzsyDQmXSLWPJhfpr2OsKBqs99S/IB0Ghtg87ix3xd96gppBm8v+vIuGYrmu+UV3CbxZWgLOx4cZni5Kwg+NYqphYnRKO7xBmER278krdpVfVu1jHDPqGUGHBpw7idmj8=
  file_glob: true
  file: /*.deb
  skip_cleanup: true
  on:
    tags: true
