sudo: required
language: cpp
services:
- docker
env:
  global:
    secure: X7vYsdnuullrVSCuHtTdO9m252YBijzqXzsaj0QIqS45vUrqafY7QS4B2/QYpEX14LN3G9/KjSO/QntY9v6xOsfH1KwhTpCRpjRataivi8uaYGK5LwL7mf3kmNeWbl4jzyUrXDcL9a2JReKlCtAGbNs73NcIMuHhXbqlJBr0Pus=
before_install:
- docker pull ubuntu:16.04
- docker pull ubuntu:14.04
script:
- docker build --tag svmtoolpp-ubuntu16 --build-arg BINTRAYKEY=$BINTRAYKEY --build-arg
  TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER -f ./Dockerfile-ubuntu16.04 .
- docker build --tag svmtoolpp-ubuntu14 --build-arg BINTRAYKEY=$BINTRAYKEY --build-arg
  TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER -f ./Dockerfile-ubuntu14.04 .
after_success:
- docker run -t -d svmtoolpp-ubuntu16
- docker cp $(docker ps -n 1 -q):/src/svmtool-cpp/build/svmtool-cpp-1.1.7-Linux.deb
  $HOME/svmtool-cpp-1.1.7-ubuntu16.deb
- docker run -t -d svmtoolpp-ubuntu14
- docker cp $(docker ps -n 1 -q):/src/svmtool-cpp/build/svmtool-cpp-1.1.7-Linux.deb
  $HOME/svmtool-cpp-1.1.7-ubuntu14.deb
before_deploy:
- git config --local user.name "Gael de Chalendar"
- git config --local user.email "kleag@free.fr"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: ZRN8Fjl12B8kuvOldwC3GGGzG/1UgWhjzJRU89Uc0hXwD/nz1SgXJChFIUmHPvzOTGQYt31Rf2ixstaYIMH5C+EpDYRx+99gyY2KtriNaD2v04208CZPSgVIaMyb/X8WO+uXXuJCpo0GGuOKYgVIZOuHgtNJ4LvBgGX4z47FBcU=
  file_glob: true
  file: $HOME/*.deb
  skip_cleanup: true
  on:
    repo: aymara/svmtool-cpp
    tags: false
    all_branches: true
