language: cpp
compiler: gcc
env:
  global:
    secure: X7vYsdnuullrVSCuHtTdO9m252YBijzqXzsaj0QIqS45vUrqafY7QS4B2/QYpEX14LN3G9/KjSO/QntY9v6xOsfH1KwhTpCRpjRataivi8uaYGK5LwL7mf3kmNeWbl4jzyUrXDcL9a2JReKlCtAGbNs73NcIMuHhXbqlJBr0Pus=
install:
- cat /etc/*-release
- echo `echo 2 | sudo update-alternatives --config gcc`
- sudo add-apt-repository --yes ppa:kubuntu-ppa/backports
- sudo apt-get update
- sudo apt-get install -qq -y cmake gdb
script: pwd && mkdir dist && mkdir build && cd build && cmake .. && make && make package
after_success:
- curl -T /home/travis/build/aymara/svmtool-cpp/build/svmtool-cpp-1.1.7-Linux.deb -ukleag:$BINTRAYKEY
  https://api.bintray.com/content/kleag/ubuntu-12.04/svmtool-cpp/$TRAVIS_JOB_NUMBER/$TRAVIS_JOB_NUMBER/svmtool++-1.1.7-Linux.deb
- curl -XPOST -ukleag:$BINTRAYKEY https://api.bintray.com/content/kleag/ubuntu-12.04/svmtool-cpp/$TRAVIS_JOB_NUMBER/publish
