on:
  push:
    branches:
    - master
    tags:
    - '*'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  QT_VERSION: "6.5"

jobs:

  #========================================================================
  debian12_svmtoolpp:
    name: "Build the package for Debian 12"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.2.0
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: true
      - name: Build image
        run: docker build -f ./Dockerfile-debian12 -t aymara/svmtoolpp-debian12:latest .
      - name: "Push image"
        run: docker push aymara/svmtoolpp-debian12:latest

  #========================================================================
  ubuntu22_04_svmtoolpp:
    name: "Build the package for Ubuntu 22.04"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.2.0
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: true
      - name: Build image
        run: docker build -f ./Dockerfile-ubuntu22.04 -t aymara/svmtoolpp-ubuntu22.04:latest .
      - name: "Push image"
        run: docker push aymara/svmtoolpp-ubuntu22.04:latest

  #========================================================================
  manylinux_2_28_svmtoolpp:
    name: "Build the package for Manylinux 2.28"
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.AYMARA_DOCKERHUB_USERNAME }}
          password: ${{ secrets.AYMARA_DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.2.0
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: true
      - name: Build image
        run: docker build -f ./Dockerfile-manylinux2.28 -t aymara/svmtoolpp-manylinux2.28-qt${QT_VERSION}:latest .
      - name: "Push image"
        run: docker push aymara/svmtoolpp-manylinux2.28-qt${QT_VERSION}:latest
